
# version: "3.8"

# services:
#   backend:
#     build:
#       context: ./backend
#     volumes:
#       - ./backend/mywebsite:/app
#     ports:
#       - "8000:8000"
#     command: python manage.py runserver 0.0.0.0:8000

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "5173:5173" 
#     volumes:
#       - ./frontend:/app  
#       - /app/node_modules
#     stdin_open: true
#     command: ["npm", "run", "dev", "--", "--host"] 

# ----------------------------with nginx ----------------------------------------------------------------

version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/mywebsite:/app
    ports:
      - "8000:8000" 
    command: python manage.py runserver 0.0.0.0:8000


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: ["npm", "run", "dev", "--", "--host"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./frontend/build:/usr/share/nginx/html 
    ports:
      - "8080:80"  
    depends_on:
      - backend
      - frontend  
